--- #YAML:1.0
name: DBIx-Admin-CreateTrivialSchema
version: 1.01
author:
  - Ron Savage <ron@savage.net.au>
abstract: |-
  Create a set of SQL create statements, and execute them
license: artistic
requires:
  Carp: 0
build_requires:
  Test::More: 0
  Test::Pod: 0
provides:
  DBIx::Admin::CreateTrivialSchema:
    file: lib/DBIx/Admin/CreateTrivialSchema.pm
    version: 1.01
generated_by: Module::Build version 0.2611
